### ISSUE TITLE
Getting identical sequence all the time...

### ISSUE THREAD

**Issue by ZhangChenyang** [karpathy/neuraltalk2#9]
Hi Andrej,
actually I am training this model using some arbitrary dataset and arbitrary features. What I did is:
: remove the CNN layer and use a [Linear(4096, D); ReLu()] instead.

But for language model (lm.sample()) on different features, I always ended up with exact the same sequences. So my question is: is this normal for the first several thousands iterations or did I overlook something?

Thanks so much!

**Comment by karpathy** [comment]
Yes this could be normal in the beginning. You'll get boring sentences first, and then the variety will increase over time. Let us know how it goes!

**Comment by ZhangChenyang** [comment]
Hi Andrej,

Yes, after overnight trainning, things get a little bit better, there are some sentences now! But however, compared to NeuralTalk V1, there are still too many UNK tokens. Is there somewhere I can tune to get rid of these? Thanks!

**Comment by karpathy** [comment]
Are you training on CPU? My guess is your code is training very slowly. To give you an idea, I go through roughly 200,000 iterations (batch size 16) before the model converges. But you should see reasonable sentences at around 50,000.

**Comment by ZhangChenyang** [comment]
I am trainning on GPU. I guess the problem probably is caused by my dataset, which is not as descriptive and well labeled as either COCO or Flickr8K.

**Comment by ZhangChenyang** [comment]
Hi Andrej，
From your experience, it the value of --max_length (prepro.py) option matters?

**Comment by karpathy** [comment]
max_length is the upper bound on the number of words that will be used from your captions. If your captions are all short you may want to decrease this, and vice versa. The model will in the beginning latch onto the most common patterns and over time relax itself to the others. If you used `-sample_max 0` flag instead you would see more samples, but then you might have to play with `temperature` to not get garbage.

Closing the issue since it's probably not an issue with the code base. Thanks!
